name: listing
on: 
  push:
    branches: ['main']
    paths:
    - '.github/workflows/listing.yaml'
    - 'plugin/README.txt'
    - '.wordpress-org/**'
jobs:
  trunk:
    name: listing
    runs-on: ['hyperenv', 'small']
    steps:
    - uses: actions/checkout@master
    - uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: attachmentav
        IGNORE_OTHER_FILES: true
        BUILD_DIR: plugin
