---
name: release
on:
  push:
    tags:        
    - 'v*'
permissions:
  id-token: write
  contents: write
defaults:
  run:
    shell: bash
jobs:
  release:
    runs-on: ['hyperenv', 'medium-eu-west-1']
    steps:
    - uses: actions/checkout@v4
    - name: Create ZIP
      run: |
        cd plugin
        zip -r ../attachmentav.zip .
        cd ..
    - name: Create release including artifact
      uses: softprops/action-gh-release@v2
      with:
        files: attachmentav.zip
    - name: Deploy to Wordpress Plugin Directory
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: attachmentav
        BUILD_DIR: plugin
        
