---
name: release
on:
  push:
    tags:        
    - 'v*'
permissions:
  id-token: write
  contents: write
defaults:
  run:
    shell: bash
jobs:
  release:
    runs-on: ['hyperenv', 'medium']
    steps:
    - uses: actions/checkout@v4
    - name: Create ZIP
      run: |
        cd plugin
        zip -r ../attachmentav.zip .
        cd ..
    - name: Create release including artifact
      uses: softprops/action-gh-release@v2
      with:
        files: attachmentav.zip
    
        
